### ISSUE TITLE
Double-clicking permanently replaces Jupyter Lab tab with local html

### ISSUE THREAD

**Issue by cooknl** [mflevine/jupyterlab_html#3] opened 2018-04-06 14:43 UTC
I successfully installed `jupyter_html` and restarted Jupyter Lab.

I saw a new icon on the filename of the local html, which was an indicator that the extension was active.

I double-clicked on the filename in the Jupyter Lab file manager.

The tab then navigated to the local html, replacing the Jupyter Lab page (an undesirable outcome).

When I used the back button, it momentarily showed the Jupyter Lab page, but then immediately navigated back to the local html (a second undesirable outcome).

I shutdown my browser and all the Jupyter Lab back end, and restarted.

Upon restarting, Jupyter Lab momentarily showed the Jupyter Lab page, but then immediately navigated to the local html (a third undesirable outcome).

I'm going to uninstall the extension now, but I'm willing to do some troubleshooting, if you can't replicate the problem.

**Comment by mflevine** [comment] 2018-04-06 20:27
Hmm I have never encountered this issue. I only really use Chrome, maybe this is browser-specific? Does this happen with every html file you have tried?

**Comment by cooknl** [comment] 2018-04-09 04:13
"Google Chrome is up to date
Version 65.0.3325.181 (Official Build) (64-bit)"
Jupyter version 4.4.0
JupyterLab v0.31.12

I only tried the one. It was debilitating enough to my workflow that I didn't try it with more than one, since I had to completely uninstall the extension to avoid the symptom.

**Comment by mflevine** [comment] 2018-10-04 00:44
Closing as I couldn't reproduce and no one else having this issue.

**Closed as completed by mflevine** 2018-10-04 00:44 UTC
